---
# vars file for nginx
DOMAIN_NAME: "{{ domain_name }}"
NGINX_CONFIG_FILE: /etc/nginx/sites-available/{{ DOMAIN_NAME }}.conf
NGINX_ENABLE_FILE: /etc/nginx/sites-enabled/{{ DOMAIN_NAME }}.conf
ENABLE_SSL: if "{{ enable_ssl }}" true else false
