version: '3'
services:
  app:
    image: rachel144/clinicserver:latest
    container_name: clinic-server-container
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - SERVER_URL=${SERVER_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always
