---
# vars file for docker
DOCKER_IMAGE_NAME: "{{ image_name }}"
DOCKERHUB_USERNAME: "{{ dockerhub_username }}"
DOCKERHUB_TOKEN: "{{ dockerhub_token }}"
DOMAIN_NAME: "{{ domain_name }}"
MONGO_URL: "{{ mongo_url }}"
JWT_SECRET: "{{ jwt_secret }}"
AWS_REGION: "{{ aws_region }}"
S3_ACCESS_KEY_ID: "{{ s3_access_key_id }}"
S3_SECRET_ACCESS_KEY: "{{ s3_secret_access_key }}"
S3_BUCKET_NAME: "{{ s3_bucket_name }}"
SERVER_URL: "{{ server_url }}"
TELEGRAM_TOKEN: "{{ telegram_token }}"
APP_PORT: 8000
